apiVersion: v1
kind: Service
metadata:
  name:  samboo-service
  namespace: samboo-ns
spec:
  type: NodePort
  selector:
    app: samboo
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000